site_name: Peyton Pope
site_url: https://peytonjpope.com
theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Roboto
  icon:
    logo: material/alpha-p-box
  favicon:
    logo: material/alpha-p-box
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.select

  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle: 
        icon: material/lightbulb-outline
        name: Dark mode
      primary: blue grey
      accent: deep purple
    
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: 
        icon: material/lightbulb
        name: Light mode
      primary: blue grey
      accent: deep purple
extra:
  generator: false 
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/peyton-pope-75202b24a/
    - icon: fontawesome/brands/github
      link: https://github.com/peytonjpope

nav:
  - Home: index.md
  - Projects:
    - SignCraft WebApp: projects/signcraft.md
    - Church Data Science: projects/churchds.md
    - Bracket Generator: projects/cfpbracket.md
    - Portfolio Website: projects/portfolio.md
  - About Me: about.md
extra_css:
  - assets/style.css

copyright: v2.0.0